export const FETCH_TASKS = 'FETCH_TASKS';
export const FETCH_TASKS_SUCCESS = 'FETCH_TASKS_SUCCESS';
export const FETCH_TASKS_FAILED = 'FETCH_TASKS_FAILED';

export const FILTER_TASKS = 'FILTER_TASKS';
export const FILTER_TASKS_SUCCESS = 'FILTER_TASKS_SUCCESS';
export const FILTER_TASKS_FAILED = 'FILTER_TASKS_FAILED';
